name: Workflow Dispatch branch detection
on:
  workflow_dispatch:

jobs:
  detection:
    runs-on: ${{ vars.RUNNER_UBUNTU }}
    steps:
      - name: Get ref by env var
        run: echo "Ref $GITHUB_REF"
      - name: Get event_name by env var
        run: echo "Event name $GITHUB_EVENT_NAME"
      - name: Get ref
        run: echo "Ref ${{ github.ref }}"
      - name: Get event_name
        run: echo "Event name ${{ github.event_name }}"
      - name: Get event.ref
        run: echo "Event ref ${{ github.event.ref }}"
